name: Infrastructure Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
#env:
 # WORK_DIR: ./learn-terraform-provision-eks-cluster
  
jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6  # Update if required

      # Step 3: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Update your AWS region

      # Step 4: Verify directory and run Terraform Init
      - name: Terraform Init
        run: terraform init
       # working-directory: ${{ env.WORK_DIR }}
      
      - name: Terraform format
        id: fmt
        run: terraform fmt
        #working-directory: ${{ env.WORK_DIR }}

      - name: Terraform Validation
        run: terraform validate
        #working-directory: ${{ env.WORK_DIR }}

      # Step 7: Terraform Plan
      - name: Terraform Plan
        id: plan
        run: terraform plan
       # working-directory: ${{ env.WORK_DIR }}

      # Step 8: Terraform Apply(if push event)
      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply
       # working-directory: ${{ env.WORK_DIR }}
